Models/ErrorViewModel.cs
namespace form_registrar_jugadores_net.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Formulario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Net.Http.Headers;

namespace form_registrar_jugadores_net.Models
{
    public class Formulario
    {
        public string? nombre {get; set;}
        public int? edad {get; set;}
        public string? genero {get; set;}
        public string? equipo {get; set;}
        public string? categoria {get; set;}
        public int num_meses {get; set;}
        public string? num_temporadas {get; set;}

        public Boolean verificar() {
            if(nombre == null || edad == null || genero == null) {
                return false;
            } else {
                return true;
            }
        }

        public double calcularPago() {
            double resultado;

            resultado = num_meses/6 * 300;

            return resultado;
        }

        public double calcularImpuesto() {
            double impuesto;

            impuesto = calcularPago()*0.19;

            return impuesto;
        }

        public double calcularMontoTotal() {
            return calcularPago() + calcularImpuesto();
        }

    }
}

Controllers/FormularioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using form_registrar_jugadores_net.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace form_registrar_jugadores_net.Controllers
{
    [Route("[controller]")]
    public class FormularioController : Controller
    {
        private readonly ILogger<FormularioController> _logger;

        public FormularioController(ILogger<FormularioController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Formulario(Formulario obj)
        {
            if(obj.verificar()) {
                ViewData["Resultado"] = 
                "<h4>Registro exitoso</h4>" + 
                "<p>Jugador: " + obj.nombre + "</p>"+
                "<p>Club: " + obj.equipo + "</p>"+
                "<p>Temporadas: " + obj.num_temporadas + "</p>" +
                "<p>Meses: " + obj.num_meses + "</p>" +
                "<p>Monto total a pagar: <br> Monto: " + obj.calcularPago() + "<br>Impuesto del 19%:  " + obj.calcularImpuesto() +  "<br>Total: " + obj.calcularMontoTotal() +"</p>";
            }else {
                ViewData["Resultado"] = "Porfavor, rellene todos los campos";
            }
            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true), Route("Error")]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using form_registrar_jugadores_net.Models;

namespace form_registrar_jugadores_net.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Formulario/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="css/form_style.css">
</head>
<body>
<div class="text-center">
    <h2 class="title">Formulario de Jugador de Futbol</h2>
    <form asp-controller="Formulario" asp-action="Formulario" method="post" class="form-container">
        <label for="nombre" class="label-text">Nombre:<br /><input type="edad" id="nombre" name="nombre"></label><br />
        <label for="edad" class="label-text">Edad:<br /><input type="edad" id="edad" name="edad"></label><br />
        <fieldset class="fs-container">
            <label class="label-text">Genero:</label><br />
            <label>
                <input type="radio" name="genero" value="Masculino"> Masculino
            </label>
            <br>
            <label>
                <input type="radio" name="genero" value="Femenino"> Femenino
            </label>
        </fieldset>
        <label for="Equipo" class="label-select">Equipo:<br />
        <select name="equipo" id="curso">
            <option value="Universitario" selected>Universitario</option>
            <option value="Alianza Lima">Alianza Lima</option>
            <option value="S. Cristal">S. Cristal</option>
            <option value="Cienciano">Cienciano</option>
            <option value="Fbc Melgar">Fbc Melgar</option>
        </select>
        </label>
            <br>
        <label for="Categoria" class="label-select">Categoria:<br />
        <select name="categoria" id="Categoria">
            <option value="Universitario" selected>Sub-15</option>
            <option value="Alianza Lima">Sub-17</option>
            <option value="S. Cristal">Sub-20</option>
            <option value="Cienciano">Sub-23</option>
        </select>
        </label>
            <br>
        <label for="numero_meses" class="label-select">Número de meses a inscribirse:<br />
        <select name="num_meses" id="numero_meses">
            <option value="6" selected>6 meses</option>
            <option value="12">12 meses</option>
            <option value="18">18 meses</option>
            <option value="24">24 meses</option>
        </select>
        </label>
            <br>
        <label for="numero_meses" class="label-select">Número de temporadas:<br />
        <select name="num_temporadas" id="numero_temporadas">
            <option value="1" selected>1 Temporada</option>
            <option value="2">2 Temporada</option>
            <option value="3">3 Temporada</option>
            <option value="4">4 Temporada</option>
        </select>
        </label>

        <br><br>
        <input type="submit" value="Enviar" class="btn-submit">
        <p style="color: rgb(110, 110, 110); font-size: 13px; margin-top: 5px">6 meses = 300 Soles</p>
        <p style="color: rgb(110, 110, 110); font-size: 13px; margin-top: -20px">+ Impuesto 19%</p>
    </form>
    <br>
    <div class="resultado">
    @Html.Raw(ViewData["Resultado"])
    </div>
</div>
</body>
</html>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - form_registrar_jugadores_net</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/form_registrar_jugadores_net.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">form_registrar_jugadores_net</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Formulario" asp-action="Formulario">Formulario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - form_registrar_jugadores_net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>